version: 2

linux_cache: &linux_cache
  keys:
    - miniconda-{{ .Environment.MINICONDA_VER }}-{{ .Environment.BIOCONDA_UTILS_TAG }}-{{ arch }}

jobs:
  # Setup Conda and bioconda-utils and store it in the common workspace
  setup:
    machine: true
    steps:
      - restore_cache:
          <<: *linux_cache
      - checkout
      - run:
          name: setup
          command: |
            if [ -d /tmp/workspace/miniconda ]; then
                # skip the following if cache was restored
                exit 0
            fi
            mkdir -p /tmp/workspace
            pip install pyyaml
            ./simulate-travis.py --bootstrap /tmp/workspace/miniconda --overwrite
            conda clean -y --all
      - save_cache:
          key: miniconda-{{ .Environment.MINICONDA_VER }}-{{ .Environment.BIOCONDA_UTILS_TAG }}-{{ arch }}
          paths:
            - /tmp/workspace/miniconda
      # store the miniconda installation in the common workspace
      # - persist_to_workspace:
      #     root: /tmp/workspace
      #     paths:
      #       - miniconda

  # Perform linting
  lint:
    machine: true
    steps:
      - restore_cache:
          <<: *linux_cache
      # - attach_workspace:
      #     at: /tmp/workspace
      - checkout
      - run: echo 'export PATH="/tmp/workspace/miniconda/bin:$PATH"' >> $BASH_ENV
      - run: bioconda-utils lint recipes config.yml --git-range master

workflows:
  version: 2
  bioconda-linux:
    jobs:
      - setup:
          context: org-global
      - lint:
          requires:
            - setup
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - bulk
