version: 2

# setup common args that are reused among jobs
common_args: &common_args
  working_directory: /tmp

# setup common workspace that is reused among jobs
common_workspace: &common_workspace
    root: workspace
    paths:
      - miniconda

jobs:
  # Setup Conda and bioconda-utils and store it in the common workspace
  setup:
    <<: *common_args
    machine: true
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: scripts/simulate-travis.py --bootstrap workspace/miniconda --overwrite
      # store the miniconda installation in the common workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - miniconda

  # Perform linting
  lint:
    <<: *common_args
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: bioconda-utils lint recipes config.yml --git-range master HEAD

workflows:
  version: 2
  bioconda-linux:
    jobs:
      - setup:
          context: org-global
      - lint:
          requires:
            - setup
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - bulk
