version: 2

variables:
  restore_cache: &restore_cache
    restore_cache:
      keys:
        - miniconda-{{ .Environment.MINICONDA_VER }}-{{ .Environment.BIOCONDA_UTILS_TAG }}-{{ arch }}
  save_cache: &save_cache
    save_cache:
      key: miniconda-{{ .Environment.MINICONDA_VER }}-{{ .Environment.BIOCONDA_UTILS_TAG }}-{{ arch }}
      paths:
        - /tmp/workspace/miniconda
  setup: &setup
    run: 
      name: Setup bioconda-utils
      command: .circleci/setup.sh
  macos: &macos
    macos:
      xcode: "9.0"
  linux: &linux
    machine: true


jobs:
  lint:
    <<: *linux
    steps:
      - *restore_cache
      - checkout
      - *setup
      - *save_cache
      - run:
          name: Linting
          command: bioconda-utils lint recipes config.yml --git-range master HEAD

  # build and test on linux
  test-linux:
    <<: *linux
    steps:
      - *restore_cache
      - checkout
      - *setup
      - *save_cache
      - run:
          name: Building and testing
          command: bioconda-utils build recipes config.yml --git-range master HEAD --docker --mulled-test

  # build and test on macos
  test-macos:
    <<: *macos
    steps:
      - *restore_cache
      - checkout
      - *setup
      - *save_cache
      - run:
          name: Building and testing
          command: bioconda-utils build recipes config.yml --git-range master HEAD

  # build, test and upload on linux
  upload-linux:
    <<: *linux
    steps:
      - *restore_cache
      - checkout
      - *setup
      - *save_cache
      # build only current commit (since we use squashed merging, this is safe
      - run:
          name: Building, testing, and uploading
          command: bioconda-utils build recipes config.yml --git-range $CIRCLE_SHA1 --docker --mulled-test --anaconda-upload --mulled-upload-target biocontainers

  # build, test and upload on macos
  upload-macos:
    <<: *macos
    steps:
      - *restore_cache
      - checkout
      - *setup
      - *save_cache
      # build only current commit (since we use squashed merging, this is safe
      - run:
          name: Building, testing and uploading
          command: bioconda-utils build recipes config.yml --git-range $CIRCLE_SHA1 --docker --anaconda-upload


workflows:
  version: 2
  # workflow for testing pushes and PRs
  bioconda-test:
    jobs:
      - lint:
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - bulk
      - test-linux:
          requires:
            - lint
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - bulk
      - test-macos:
          requires:
            - lint
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - bulk
  # workflow for uploading packages from master and bulk branch
  #  bioconda-upload:
  #    jobs:
  #      - upload-linux:
  #        context: org-global
  #        filters:
  #          branches:
  #            only:
  #              - master
  #              - bulk
  #      - upload-macos:
  #          context: org-global
  #          filters:
  #            branches:
  #             only:
  #               - master
  #                - bulk
