version: 2

jobs:
  # Setup Conda and bioconda-utils and store it in the common workspace
  setup:
    machine: true
    environment:
      - MINICONDA_VER: "4.3.21"
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace
      - run: pip install pyyaml
      - run: ./simulate-travis.py --bootstrap /tmp/workspace/miniconda --overwrite
      # store the miniconda installation in the common workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - miniconda

  # Perform linting
  lint:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: echo 'export PATH="/tmp/workspace/miniconda/bin:$PATH"' >> $BASH_ENV
      - run: bioconda-utils lint recipes config.yml --git-range master HEAD

workflows:
  version: 2
  bioconda-linux:
    jobs:
      - setup:
          context: org-global
      - lint:
          requires:
            - setup
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - bulk
