version: 2

variables:
  linux_cache: &linux_cache
    keys:
      - miniconda-{{ .Environment.MINICONDA_VER }}-{{ .Environment.BIOCONDA_UTILS_TAG }}-{{ arch }}
      


jobs:
  # Setup Conda and bioconda-utils and store it in the common workspace
  setup-linux:
    machine: true
    steps:
      - restore_cache:
          <<: *linux_cache
      - checkout
      - run:
          name: setup
          command: .circleci/setup-conda.sh
      - save_cache:
          key: miniconda-{{ .Environment.MINICONDA_VER }}-{{ .Environment.BIOCONDA_UTILS_TAG }}-{{ arch }}
          paths:
            - /tmp/workspace/miniconda

  lint:
    machine: true
    steps:
      - restore_cache:
          <<: *linux_cache
      - checkout
      - run: .circleci/setup-env.sh
      - run: bioconda-utils lint recipes config.yml --git-range master HEAD

  test-linux:
    machine: true
    steps:
      - restore_cache:
          <<: *linux_cache
      - checkout
      - run: .circleci/setup-env.sh
      - run: bioconda-utils build recipes config.yml --git-range master HEAD --docker --mulled-test

workflows:
  version: 2
  bioconda-linux:
    jobs:
      - setup-linux:
          context: org-global
      - lint:
          requires:
            - setup-linux
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - bulk
      - test-linux:
          requires:
            - lint
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - bulk

