version: 2

variables:
  restore_cache: &restore_cache
    restore_cache:
      keys:
        - miniconda-{{ .Environment.MINICONDA_VER }}-{{ .Environment.BIOCONDA_UTILS_TAG }}-{{ arch }}
  save_cache: &save_cache
    save_cache:
      key: miniconda-{{ .Environment.MINICONDA_VER }}-{{ .Environment.BIOCONDA_UTILS_TAG }}-{{ arch }}
      paths:
        - /tmp/workspace/miniconda
  setup: &setup
    run: 
      name: Setup bioconda-utils
      command: .circleci/setup.sh
  macos: &macos
    macos:
      xcode: "9.0"
  linux: &linux
    docker:
      - image: circleci/python:3


jobs:
  # When running CircleCI locally, we put everything in one job.
  build:
    docker:
      # TODO use a prebuild image
      - image: circleci/python:3
    steps:
      - setup_remote_docker
      - checkout
      - *setup
      - run:
          name: Linting
          command: bioconda-utils lint recipes config.yml --git-range master HEAD
      - run:
          name: Testing
          # Currently, using --docker below causes a permission error on Fedora 27, 
          # although it should be supported by the setup_remote_docker directive 
          # above. A workaround or an upstream fix would be welcome.
          command: bioconda-utils build recipes config.yml --git-range master HEAD

  lint:
    <<: *linux
    steps:
      - *restore_cache
      - checkout
      - *setup
      - *save_cache
      - run:
          name: Linting
          command: bioconda-utils lint recipes config.yml --git-range master HEAD

  # build and test on linux
  test-linux:
    <<: *linux
    steps:
      - setup_remote_docker
      - *restore_cache
      - checkout
      - *setup
      - *save_cache
      - run:
          name: Building and testing
          command: bioconda-utils build recipes config.yml --git-range master HEAD --docker --mulled-test

  # build and test on macos
  test-macos:
    <<: *macos
    steps:
      - checkout
      # We cannot cache the miniconda installation on macos.
      # The reason is that tar seems to have a bug when handling sym and hardlinks in the miniconda installation.
      # The error is, e.g.: Cannot extract through symlink tmp/workspace/miniconda/LICENSE.rst
      - *setup
      - run:
          name: Building and testing
          command: bioconda-utils build recipes config.yml --git-range master HEAD

  # build, test and upload on linux
  upload-linux:
    <<: *linux
    steps:
      - setup_remote_docker
      - *restore_cache
      - checkout
      - *setup
      - *save_cache
      # build only current commit (since we use squashed merging, this is safe
      - run:
          name: Building, testing, and uploading
          command: bioconda-utils build recipes config.yml --git-range $CIRCLE_SHA1 --docker --mulled-test --anaconda-upload --mulled-upload-target biocontainers

  # build, test and upload on macos
  upload-macos:
    <<: *macos
    steps:
      - checkout
      - *setup
      # build only current commit (since we use squashed merging, this is safe
      - run:
          name: Building, testing and uploading
          command: bioconda-utils build recipes config.yml --git-range $CIRCLE_SHA1 --docker --anaconda-upload


workflows:
  version: 2
  # workflow for testing pushes and PRs
  bioconda-test:
    jobs:
      - lint:
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - bulk
      - test-linux:
          requires:
            - lint
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - bulk
      - test-macos:
          requires:
            - lint
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - bulk
  # workflow for uploading packages from master and bulk branch
  bioconda-upload:
    jobs:
      - upload-linux:
          context: org-global
          filters:
            branches:
              only:
                - master
                - bulk
      - upload-macos:
          context: org-global
          filters:
            branches:
              only:
                - master
                - bulk
